apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: performance-lab
  labels:
    app: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: ghcr.io/shriramgokhalemalya/login-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: login-service-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_SECONDS
              value: "3600"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
